name: DivictusInterfacePlugin
version: 0.2
author: Anatomic
main: me.anatomic.divictus.interfaceplugin.InterfacePlugin
api-version: 1.8
depend: [ProtocolLib]
commands:
  notes:
    description: Notes for the user from the Staff
    usage: /<command> player page
    permission: divictusinterface.notes
  pinfo:
    description: Get Information about a player
    usage: /<command> player
    permission: divictusinterface.playerinfo
  newnote:
    description: Create a note about a user.
    permission: divictusinterface.notes
    usage: /<command> user and you write your note
  report:
    description: Report players to the Staff of the Network.
    usage: /<command> player reason
  blockreports:
    description: Block Network-wide a player from reporting.
    permission: divictusinterface.reportcontrol
    usage: /<command> player
  allowreports:
    description: Allow Network-wide a player to report
    permission: divictusinterface.reportcontrol
    usage: /<command> player
  resolvereports:
    description: Resolves all reports about a certain player.
    permission: divictus.resolvereports
    usage: /<command> player
  interfaceinfo:
    description: Command that gives you information about the Interface.
    usage: /<command>

permissions:
  divictusinterface.notes:
    description: You can add notes about users!
  divictusinterface.reportcontrol:
    description: You can block and allow players from reporting.
  divictusinterface.playerinfo:
    description: You can get information about players from the Interface
  divictus.resolvereports:
    description: Allows the staff to resolve all reports about a player